use_frameworks!

platform :ios, '9.0'

target 'ORCarousel_Example' do
  pod 'ORCarousel', :path => '../'

  target 'ORCarousel_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
